### ISSUE TITLE
Supporting lineWrap?

### ISSUE THREAD

**Issue by mehulmpt** [datavis-tech/vizhub-io#30]
Hey! I'm really interested in CM6 and wanted to ask a quick question. I understand it is still very much under development but is there any way to support line wrapping at the moment?

**Comment by curran** [comment]
@mehulmpt I suggest you post the same issue over here --> https://github.com/codemirror/codemirror.next

**Comment by curran** [comment]
This repo `datavis-tech/codemirror-6-experiments` is just my personal playground for experimenting, mainly with real-time collaboration.

**Comment by mehulmpt** [comment]
Got you
